### PR TITLE
Fix current events queries

### PR DESCRIPTION
**Pull request by fg-devs**

### CODE REVIEW

**Comment by fg-devs** [comment]
@kwark Hey. I have seen you made changes to fix the current events queries, but unfortunately it still doesn't seem to work.

If you check out the tests in this PR, i changed it to persist 500 events and run the query, if you do that on the develop branch right now, you will see that it will not work as expected (you get only 16 events).

**Comment by fg-devs** [comment]
Ah there is actually another problem, stream may not finish if subscriber doesn't pull, checking it.

**Comment by kwark** [comment]
@fg-devs thanks for looking into this: if the current event queries still have problems with the current setup: ActorPublisher requesting replay from the write journal actor, we might also consider an alternative and query the database directly using Slick and transform that to a Akka stream.

**Comment by fg-devs** [comment]
@kwark Yes that was what I also thought about. Would make things easier as well. I will take a look into that.

**Comment by fg-devs** [comment]
@kwark Updated it to directly stream from slick.

**Pull request merged**
